service: serverless-nestjs

provider:
  name: aws
  runtime: nodejs8.10
  stage: v1
  region: cn-northwest-1
  endpointType: regional

plugins:
  - serverless-offline
  - serverless-apigw-binary

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - nodemon.json
    - README.md

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  index:
    handler: dist/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any
